import { AlertTriangle, FlaskConical } from 'lucide-react';
import { cn } from '@/lib/utils';
import { productCutout } from '@/lib/productImages';
import {
  buildProtocolPlan,
  type ProtocolPlanStep,
} from '@/lib/xcapeRules/protocolPlan';
import type {
  ProtocolDisplayAddon,
  ProtocolDisplayProduct,
} from '@/components/xcape/protocol/ProtocolRecommendations';

/**
 * "Your XCAPE Protocol" — the single client-facing presentation of the
 * deterministic protocol: what the scan found, which XCAPE product answers
 * it, the role it plays, when and how often to use it, and — for the two
 * customizable products only — the exact solution and dose the practitioner
 * approved.
 *
 * Nothing here is generated by generic AI and nothing is invented: every
 * product, dose and companion comes from the resolver / immutable snapshot.
 * Unmapped products render the explicit mapping-required state instead of a
 * guessed role.
 */

interface Props {
  face: ProtocolDisplayProduct[];
  body: ProtocolDisplayProduct[];
  addons?: ProtocolDisplayAddon[];
  tone?: 'light' | 'dark';
  /** Status line under the heading (approval / purchasability context). */
  footnote?: string;
  className?: string;
}

const Step = ({ step, dark }: { step: ProtocolPlanStep; dark: boolean }) => {
  const src = productCutout(step.product_name, step.product_image_url);
  return (
    <li className="flex items-start gap-4 py-4 first:pt-1 sm:gap-5">
      <div className="flex w-14 shrink-0 flex-col items-center gap-1 sm:w-16">
        <span
          className={cn(
            'text-[10px] font-semibold uppercase tracking-[0.16em]',
            dark ? 'text-slate-500' : 'text-muted-foreground/70',
          )}
        >
          Step {step.step}
        </span>
        {src ? (
          <img
            src={src}
            alt={step.product_name}
            loading="lazy"
            className="h-20 w-14 object-contain object-center sm:h-24 sm:w-16"
          />
        ) : null}
      </div>

      <div className="min-w-0 flex-1 space-y-1">
        <div className="flex flex-wrap items-baseline gap-x-2">
          <p className={cn('text-sm font-medium', dark ? 'text-slate-100' : 'text-foreground')}>
            {step.product_name}
          </p>
          {step.role && (
            <span
              className={cn(
                'text-[10px] uppercase tracking-[0.16em]',
                dark ? 'text-sky-300' : 'text-primary',
              )}
            >
              {step.role}
            </span>
          )}
          <span
            className={cn(
              'text-[10px] uppercase tracking-[0.16em]',
              dark ? 'text-slate-500' : 'text-muted-foreground/70',
            )}
          >
            {step.area === 'body' ? 'Body' : 'Face'}
          </span>
        </div>

        {step.mapping_required ? (
          <p
            className={cn(
              'flex items-start gap-1.5 text-[12px]',
              dark ? 'text-amber-300' : 'text-amber-700',
            )}
          >
            <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" aria-hidden />
            XCAPE product/kit mapping required — usage guidance is confirmed by XCAPE before this
            product is prepared or purchased.
          </p>
        ) : (
          <>
            {step.rationale && (
              <p className={cn('text-[12.5px]', dark ? 'text-slate-300' : 'text-muted-foreground')}>
                {step.rationale}
              </p>
            )}
            {(step.when || step.frequency) && (
              <p
                className={cn(
                  'text-[11.5px]',
                  dark ? 'text-slate-400' : 'text-muted-foreground/80',
                )}
              >
                {[step.when, step.frequency].filter(Boolean).join(' · ')}
              </p>
            )}
          </>
        )}

        {step.concerns.length > 0 && (
          <p className={cn('text-[11px]', dark ? 'text-slate-500' : 'text-muted-foreground/70')}>
            For: {step.concerns.join(' · ')}
          </p>
        )}

        {step.customization.length > 0 && (
          <div
            className={cn(
              'mt-2 rounded-xl border p-3',
              dark ? 'border-slate-700/80 bg-slate-900/50' : 'border-border/60 bg-muted/40',
            )}
          >
            <p
              className={cn(
                'text-[10px] font-semibold uppercase tracking-[0.16em]',
                dark ? 'text-slate-400' : 'text-muted-foreground',
              )}
            >
              Customized for you with
            </p>
            <ul className="mt-1 space-y-1">
              {step.customization.map((c, i) => (
                <li
                  key={`${c.ds_name}-${c.concern}-${i}`}
                  className={cn(
                    'flex flex-wrap items-baseline gap-x-2 text-[12.5px]',
                    dark ? 'text-slate-300' : 'text-muted-foreground',
                  )}
                >
                  <span className={dark ? 'text-slate-100' : 'text-foreground'}>
                    {c.ds_name}
                    {c.companion && ' (required companion)'}
                  </span>
                  <span
                    className={cn(
                      'font-semibold tabular-nums',
                      dark ? 'text-slate-50' : 'text-foreground',
                    )}
                  >
                    {c.dose_ml} ml
                  </span>
                  <span className="text-[11px]">
                    {c.concern}
                    {typeof c.score === 'number' ? ` · score ${c.score}/100` : ''}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </li>
  );
};

const ClientProtocolPlan = ({
  face,
  body,
  addons = [],
  tone = 'light',
  footnote,
  className,
}: Props) => {
  const plan = buildProtocolPlan({ face, body, addons });
  if (plan.steps.length === 0) return null;
  const dark = tone === 'dark';

  return (
    <section
      aria-label="Your XCAPE protocol"
      className={cn(
        'space-y-4 rounded-2xl border p-4',
        dark ? 'border-slate-700/80 bg-[#101214]' : 'border-border/60 bg-card/50',
        className,
      )}
    >
      <div className="space-y-1">
        <h3
          className={cn(
            'flex items-center gap-1.5 text-sm font-semibold',
            dark ? 'text-slate-50' : 'text-foreground',
          )}
        >
          <FlaskConical className="h-4 w-4 shrink-0" aria-hidden /> Your XCAPE protocol
        </h3>
        <p className={cn('text-[11.5px]', dark ? 'text-slate-400' : 'text-muted-foreground')}>
          {footnote ??
            'Built from your four skin-health scores using the XCAPE customization protocol. Use the steps in order. Only your Face Cream and Body Milk are customized — body is prepared at 3× the face dose.'}
        </p>
      </div>

      {plan.mapping_required && (
        <p
          className={cn(
            'flex items-start gap-1.5 rounded-xl border p-3 text-[12px]',
            dark
              ? 'border-amber-500/40 bg-amber-500/10 text-amber-200'
              : 'border-amber-500/40 bg-amber-500/10 text-amber-800',
          )}
        >
          <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" aria-hidden />
          XCAPE product/kit mapping required for part of this protocol. XCAPE confirms the mapping
          before that item can be approved or purchased.
        </p>
      )}

      <ul className={cn('divide-y', dark ? 'divide-slate-800' : 'divide-border/50')}>
        {plan.steps.map((s) => (
          <Step key={`${s.area}-${s.product_name}`} step={s} dark={dark} />
        ))}
      </ul>
    </section>
  );
};

export default ClientProtocolPlan;
