import { FlaskConical } from 'lucide-react';
import { cn } from '@/lib/utils';

/**
 * Display shape shared by the staff resolver and the server-derived public
 * payload. Deliberately id-free and price-free: the protocol view shows
 * product name, concern, DS solution, exact ml, tier and usage area only.
 */
export interface ProtocolDisplayAddition {
  concern: string;
  ds_name: string;
  dose_ml: number;
  tier_label: string;
  score: number;
  companion: boolean;
}

export interface ProtocolDisplayProduct {
  product_name: string;
  /** Official XCAPE packaging image from the product configuration. */
  product_image_url?: string | null;
  area: 'face' | 'body';
  additions: ProtocolDisplayAddition[];
}


interface Props {
  face: ProtocolDisplayProduct[];
  body: ProtocolDisplayProduct[];
  tone?: 'light' | 'dark';
  /** Shown under the heading; explains approval / purchasability status. */
  footnote?: string;
  className?: string;
}

const AreaGroup = ({
  title,
  subtitle,
  items,
  tone,
}: {
  title: string;
  subtitle: string;
  items: ProtocolDisplayProduct[];
  tone: 'light' | 'dark';
}) => {
  if (items.length === 0) return null;
  const dark = tone === 'dark';
  return (
    <div className="space-y-2">
      <div className="flex flex-wrap items-baseline gap-x-2">
        <h4
          className={cn(
            'text-[11px] font-semibold uppercase tracking-[0.16em]',
            dark ? 'text-slate-400' : 'text-muted-foreground',
          )}
        >
          {title}
        </h4>
        <span className={cn('text-[11px]', dark ? 'text-slate-500' : 'text-muted-foreground/80')}>
          {subtitle}
        </span>
      </div>
      <ul className="space-y-2">
        {items.map((p) => (
          <li
            key={`${p.area}-${p.product_name}`}
            className={cn(
              'flex gap-3 rounded-2xl border p-3 sm:gap-4 sm:p-4',
              dark ? 'border-slate-700/80 bg-slate-900/40' : 'border-border/60 bg-surface/40',
            )}
          >
            {p.product_image_url && (
              <img
                src={p.product_image_url}
                alt={p.product_name}
                loading="lazy"
                className={cn(
                  'h-16 w-16 shrink-0 rounded-xl border object-cover sm:h-20 sm:w-20',
                  dark ? 'border-slate-700/80' : 'border-border/60',
                )}
              />
            )}
            <div className="min-w-0 flex-1">
              <p
                className={cn(
                  'text-sm font-medium',
                  dark ? 'text-slate-100' : 'text-foreground',
                )}
              >
                {p.product_name}
              </p>
              <p
                className={cn(
                  'text-[10px] uppercase tracking-[0.16em]',
                  dark ? 'text-slate-500' : 'text-muted-foreground/80',
                )}
              >
                Customized for you with
              </p>
              <ul className="mt-1.5 space-y-1.5">
                {p.additions.map((a, i) => (
                  <li
                    key={`${a.ds_name}-${a.concern}-${i}`}
                    className={cn(
                      'flex flex-wrap items-baseline gap-x-2 gap-y-0.5 text-[12.5px]',
                      dark ? 'text-slate-300' : 'text-muted-foreground',
                    )}
                  >
                    <span className={dark ? 'text-slate-100' : 'text-foreground'}>
                      {a.ds_name}
                      {a.companion && ' (companion)'}
                    </span>
                    <span
                      className={cn(
                        'font-semibold tabular-nums',
                        dark ? 'text-sky-300' : 'text-primary',
                      )}
                    >
                      {a.dose_ml} ml
                    </span>
                    <span className="text-[11px]">
                      {a.concern} · score {a.score}/100 · tier {a.tier_label}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          </li>
        ))}
      </ul>

    </div>
  );
};

/**
 * The deterministic XCAPE protocol recommendation, grouped FACE and BODY.
 * Nothing here is generated by generic AI: products, DS solutions and doses
 * come from the confirmed protocol and the admin-maintained alignment map.
 */
const ProtocolRecommendations = ({ face, body, tone = 'light', footnote, className }: Props) => {
  if (face.length === 0 && body.length === 0) return null;
  const dark = tone === 'dark';
  return (
    <section
      aria-label="XCAPE protocol recommendations"
      className={cn(
        'space-y-4 rounded-2xl border p-4',
        dark ? 'border-slate-700/80 bg-[#101214]' : 'border-border/60 bg-card/50',
        className,
      )}
    >
      <div className="space-y-1">
        <h3
          className={cn(
            'flex items-center gap-1.5 text-sm font-semibold',
            dark ? 'text-slate-50' : 'text-foreground',
          )}
        >
          <FlaskConical className="h-4 w-4 shrink-0" aria-hidden /> XCAPE protocol recommendations
        </h3>
        <p className={cn('text-[11.5px]', dark ? 'text-slate-400' : 'text-muted-foreground')}>
          {footnote ??
            'Derived from your four health scores using the confirmed XCAPE customization protocol. Body is always recommended alongside face at 3× the face dose.'}
        </p>
      </div>
      <AreaGroup title="Face" subtitle="applied to facial skin" items={face} tone={tone} />
      <AreaGroup title="Body" subtitle="3× the face dose" items={body} tone={tone} />
    </section>
  );
};

export default ProtocolRecommendations;
