import { LayoutTemplate } from 'lucide-react';
import XcapePlaceholder from '@/components/xcape/XcapePlaceholder';

/** Report Templates — planned capability, clearly labelled. */
const XcapeAdminReportTemplates = () => (
  <XcapePlaceholder
    icon={LayoutTemplate}
    title="Report Templates"
    description="Reports are currently generated by the fixed XCAPE report system. Editable report templates and layout management are a planned capability; no report behaviour has changed."
  />
);

export default XcapeAdminReportTemplates;
