// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Sign in and reconnect." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in staff user's id, email, and staff role (if any).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data: staff } = await sb.from("staff_users").select("id, full_name, email, role, active").eq("id", ctx.getUserId()).maybeSingle();
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            { user_id: ctx.getUserId(), email: ctx.getUserEmail(), staff: staff ?? null },
            null,
            2
          )
        }
      ],
      structuredContent: { user_id: ctx.getUserId(), email: ctx.getUserEmail(), staff }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.23.8";
var list_clients_default = defineTool2({
  name: "list_clients",
  title: "List clients",
  description: "List clients visible to the signed-in staff user. Supports a text search across full name, phone, and email, and a status filter. Results respect the app's row-level security.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Case-insensitive substring match on name, phone, or email."),
    status: z.string().trim().min(1).optional().describe("Optional client status filter (e.g. `active`)."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return. Default 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let q = sb.from("clients").select("id, full_name, phone, email, status, source_type, created_at").eq("archived", false).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (search) {
      const s = search.replace(/[,%()]/g, " ");
      q = q.or(
        `full_name.ilike.%${s}%,phone.ilike.%${s}%,email.ilike.%${s}%`
      );
    }
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-client.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.23.8";
var get_client_default = defineTool3({
  name: "get_client",
  title: "Get client",
  description: "Fetch a single client by id, with recent visits and upcoming appointments.",
  inputSchema: {
    client_id: z2.string().uuid().describe("The client's UUID (from list_clients).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const [clientRes, visitsRes, apptsRes] = await Promise.all([
      sb.from("clients").select("*").eq("id", client_id).maybeSingle(),
      sb.from("client_visit_logs").select("id, visited_at, status, notes").eq("client_id", client_id).order("visited_at", { ascending: false }).limit(10),
      sb.from("appointments").select("id, scheduled_at, status, service_id, notes").eq("client_id", client_id).gte("scheduled_at", (/* @__PURE__ */ new Date()).toISOString()).order("scheduled_at", { ascending: true }).limit(10)
    ]);
    if (clientRes.error) return errorResult(clientRes.error.message);
    if (!clientRes.data) return errorResult("Client not found or not visible to this user.");
    const payload = {
      client: clientRes.data,
      recent_visits: visitsRes.data ?? [],
      upcoming_appointments: apptsRes.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.23.8";
var list_appointments_default = defineTool4({
  name: "list_appointments",
  title: "List appointments",
  description: "List appointments in a date range. Defaults to the next 7 days from now. Respects row-level security for the signed-in staff user.",
  inputSchema: {
    from: z3.string().datetime().optional().describe("ISO datetime lower bound. Defaults to now."),
    to: z3.string().datetime().optional().describe("ISO datetime upper bound. Defaults to now + 7 days."),
    client_id: z3.string().uuid().optional().describe("Only appointments for this client."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, client_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const fromIso = from ?? (/* @__PURE__ */ new Date()).toISOString();
    const toIso = to ?? new Date(Date.now() + 7 * 24 * 60 * 60 * 1e3).toISOString();
    let q = sb.from("appointments").select("id, client_id, service_id, scheduled_at, status, notes").gte("scheduled_at", fromIso).lte("scheduled_at", toIso).order("scheduled_at", { ascending: true }).limit(limit ?? 50);
    if (client_id) q = q.eq("client_id", client_id);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { from: fromIso, to: toIso, appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-visits.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.23.8";
var list_visits_default = defineTool5({
  name: "list_visits",
  title: "List visits",
  description: "List client visit logs for a given client, most recent first. Respects row-level security.",
  inputSchema: {
    client_id: z4.string().uuid().describe("The client whose visits to list."),
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("client_visit_logs").select("id, visited_at, status, notes, created_at").eq("client_id", client_id).order("visited_at", { ascending: false }).limit(limit ?? 25);
    if (error) return errorResult(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { visits: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "opdjgzditmzuxygsgybx";
var mcp_default = defineMcp({
  name: "tropics-medspa-mcp",
  title: "Tropics MedSpa",
  version: "0.1.0",
  instructions: "Tools for Tropics MedSpa staff. All calls run as the signed-in staff user and respect the app's row-level security. Use `whoami` to verify the connection, `list_clients` to browse clients, `get_client` for one client, `list_appointments` for scheduling, and `list_visits` for visit history.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_clients_default, get_client_default, list_appointments_default, list_visits_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
